version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "counter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o7kw4beqpta9"
s3_prefix = "counter"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApplicationName=\"counter\""
image_repositories = []
